return {
  mode = '',
  git = {
    branch = '',
    added = '+',
    changed = '~',
    removed = '-',
  },
  diag = {
    error = '󰅚',
    warning = '󰀪',
    info = '󰋽',
    hint = '󰌶',
  },
  format = {
    unix = '',
    dos = '',
    mac = '',
  },
  obsession = {
    active = '$',
    inactive = '',
  },
  vimtex = {
    main = '',
    sub_local = 'l',
    sub_main = 'm',
    viewer = 'v',
    continuous = 'c',
    compiled = 'c:',
  },
  seperators = {
    vert = '│',
    left = '',
    right = '',
    block = '█',
    half_block_left = '▌',
    half_block_right = '▐',
    left_filled = '',
    right_filled = '',
    slant_left = '',
    slant_left_thin = '',
    slant_right = '',
    slant_right_thin = '',
    slant_left_2 = '',
    slant_left_2_thin = '',
    slant_right_2 = '',
    slant_right_2_thin = '',
    left_rounded = '',
    left_rounded_thin = '',
    right_rounded = '',
    right_rounded_thin = '',
    circle = '●',
  },
}
